language: node_js
node_js:
  - "6"
install:
  - npm install -g elm elm-test@0.19.0-rev3 elm-format@0.8.1 elm-analyse@0.16.1
  - elm make
script:
  - elm-test
  - elm-format . --validate
  - elm-analyse .